/*
 *README 
 * 
 * 
 * BOSS:
 * THIS IS GOING TO LABEL EXACTLY WHAT THE BOSS IS GOING TO BE DOING
 * 
 * MOVEMENT:
 * FOLLOW A SERIES OF OBJECTS LAID OUT ON THE MAP (INFINITY SIGN)
 * 
 * ATTACK FUNCTION:
 * SHOOTS OUT A SERIES OF BULLETS; SHOOT OUT IN 12 OR 8 DIRECTIONS(CIRCLE)
 * 
 * SPAWNS SMALLER ENEMIES:
 * ONCE HE IS HURT ENOUGH(ABOUT 3 TIMES DURING HIS LIFETIME) THE BOSS WILL LAND ON THE GROUND AND SPAWN A WAVE
 * OF SMALLER ENEMIES
 * 
 * EXPLAINED:
 * - BOSS IS REGULARLY FOLLOWING THE PATH, THIS WILL HAPPEN AS LONG AS THE BOOL RETURNS FALSE
 * - ONCE OBJECT REACHES A CERTAIN POINT IN ITS HEALTH, THE PATH FUNCTION WILL BE CANCELED BY CHANGING THE BOOL TO TRUE
 * - THE BOOL WILL STAY TRUE UNTIL THE BOSS REACHES THE GIVEN TARGET AND SPAWNS THE ENEMIES
 * - ONCE THIS IS DONE; THE BOOL WILL RETURN TO FALSE AND THE GAME WILL KEEP GOING
 * 
 * 
 * SMALLER ENEMIES(HEALTH):
 * SMALLER ENEMIES WILL HAVE LESS HEALTH
 * 
 * NOTE: PARAM WILL WORK ON THE REST OF THE FUNCTIONS FOR NOW
 * 
 *
 */
